# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://192.168.235.132:3306/wms?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
                username: root
                password: 123456
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username:
                password:
            statViewServlet:
                # 控制台管理用户名和密码
                login-username:
                login-password:
    # redis 配置
    redis:
        # 地址
        host: 192.168.235.132
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 1
        # 密码
        password:
ruoyi:
    # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
    profile: C:/ruoyi/uploadPath
scheduling:
    enabled: false
